apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: redis-ns
data:
  sentinel.conf: |
    port 5000
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel monitor mymaster redis-0.redis.redis-ns.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
    sentinel auth-pass mymaster {{REDIS_PASSWORD}}