apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-ns
data:
  redis.conf: |
    cluster-enabled no
    cluster-config-file nodes.conf
    cluster-node-timeout 15000
    bind 0.0.0.0
    port 6379

    # Persistenza dei dati
    dir /data
    dbfilename dump.rdb
    appendonly yes
    appendfilename "appendonly.aof"